version: '3'
services:
  # web service.
  web:
    # Uses an image that’s built from the Dockerfile in the current directory.
    build: .
    # Forwards the exposed port 5000 on the container to port 5000 on the host machine. We use the default port for the Flask web server, 5000.
    ports:
     - "5000:5000"
  # redis service.
  redis:
    # The redis service uses a public Redis image pulled from the Docker Hub registry.
    image: "redis:alpine"
